name: 'Sub-dir action with recursive run'
description: 'Sub-dir action with recursive run'

runs:
  using: composite
  steps:
  - name: Print action dir
    shell: bash
    env:
      action_dir: ${{ github.action_path }}
    run: |
      echo "Recursive action dir: '${action_dir}'"
  - name: Run recursive action
    uses: ./
    with:
      uses: "dir:${{ github.action_path }}/deep"